"""lineitem price to integer

Revision ID: aeb2ec4e1404
Revises: 7aafd5d0f708
Create Date: 2021-11-11 21:45:51.863921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aeb2ec4e1404'
down_revision = '7aafd5d0f708'
branch_labels = None
depends_on = None


def upgrade():
    # Before changing column type, multiply values by 100 in order to turn euros into cents
    # In case there are floating point inaccuracies, this should truncate correctly
    op.execute('''UPDATE receiptline SET amount = amount * 100''')

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receiptline', 'amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receiptline', 'amount',
               existing_type=sa.Integer(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###

    # divide by 100 to get correct number
    op.execute('''UPDATE receiptline SET amount = amount / 100.0 ''')
